//! Simplified Chinese message registry for user-facing TUI strings.
//!
//! Machine-facing identifiers, protocol values, paths, and raw tool output do
//! not pass through this registry.
use std::borrow::Cow;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MessageId {
    ComposerPlaceholder,
    CmdCostDescription,
    CmdExitDescription,
    CmdHelpDescription,
    CmdCostReport,
    // Canonical foreground slash-command presentation.
    CanonicalCommandRequired,
    CanonicalCommandUnknown,
    CanonicalCommandNoArguments,
    CanonicalCommandListTitle,
    CanonicalCommandAliases,
    FooterWorkspacePrefix,
    // Onboarding screens — welcome.
    OnboardPanelTitle,
    OnboardStepProgress,
    OnboardHomeDirectoryNotFound,
    OnboardWelcomeVersion,
    OnboardWelcomeLead,
    OnboardWelcomeSetupBlurb,
    OnboardWelcomeSteps,
    OnboardWelcomeStepApiKey,
    OnboardWelcomeStepTrust,
    OnboardWelcomeStepTips,
    OnboardWelcomeDefaults,
    OnboardWelcomeEnter,
    OnboardWelcomeExit,
    OnboardApiKeyTitle,
    OnboardApiKeyStep1,
    OnboardApiKeyStep2,
    OnboardApiKeySavedHint,
    OnboardApiKeyFormatHint,
    OnboardApiKeyPlaceholder,
    OnboardApiKeyLabel,
    OnboardApiKeyFooter,
    OnboardApiKeyEmpty,
    OnboardApiKeyWhitespace,
    OnboardApiKeyShortWarning,
    OnboardApiKeyUnusualWarning,
    // Onboarding screens — workspace trust prompt.
    OnboardTrustTitle,
    OnboardTrustQuestion,
    OnboardTrustLocationPrefix,
    OnboardTrustRiskHint,
    OnboardTrustEffectHint,
    OnboardTrustFooterPrefix,
    OnboardTrustFooterMiddle,
    OnboardTrustFooterSuffix,
    OnboardTrustConfirmHint,
    OnboardTrustSaveFailed,
    // Onboarding screens — final tips screen.
    OnboardTipsTitle,
    OnboardTipsLine1,
    OnboardTipsLine2,
    OnboardTipsLine3,
    OnboardTipsLine4,
    OnboardTipsFooterEnter,
    OnboardTipsFooterAction,
    // Retained canonical TUI foreground.
    CanonicalWorkspaceCanonicalizeFailed,
    CanonicalWorkspaceNotDirectory,
    CanonicalNoRecoverableRun,
    CanonicalRecoveringInterruptedRun,
    CanonicalInitialCommandConfirmation,
    CanonicalUnknownValue,
    CanonicalUnknownBillingCreation,
    CanonicalAmbiguousPendingCreations,
    CanonicalAmbiguousPendingCreationsMore,
    CanonicalCancelAwaitTerminal,
    CanonicalWaitTerminalBeforeExit,
    CanonicalInterruptAccepted,
    CanonicalWaitTerminal,
    CanonicalCancelBeforeExit,
    CanonicalHelpShown,
    CanonicalCostShown,
    CanonicalSteerSubmitFailed,
    CanonicalWaitBeforeNextInput,
    CanonicalRunSubmitFailed,
    CanonicalLegacyActionUnavailable,
    CanonicalMismatchedInteractionReceipt,
    // Approval dialog — risk badges, category labels, field labels, options.
    ApprovalRiskReview,
    ApprovalRiskElevated,
    ApprovalRiskDestructive,
    ApprovalCategorySafe,
    ApprovalCategoryFileWrite,
    ApprovalCategoryShell,
    ApprovalCategoryNetwork,
    ApprovalCategoryMcpRead,
    ApprovalCategoryMcpAction,
    ApprovalCategoryAgent,
    ApprovalCategoryUnknown,
    ApprovalFieldType,
    ApprovalFieldAbout,
    ApprovalFieldImpact,
    ApprovalFieldParams,
    ApprovalOptionApproveOnce,
    ApprovalOptionDeny,
    ApprovalOptionAbortTurn,
    ApprovalControlsHint,
    ApprovalIntentLabel,
    ApprovalMoreLines,
    ApprovalEmptyContent,
    ApprovalMorePatchLines,
    ApprovalMoreFiles,
    ApprovalUnknownFile,
    // Approval dialog — localized descriptions.
    ApprovalDescSafe,
    ApprovalDescFileWrite,
    ApprovalDescShell,
    ApprovalDescNetwork,
    ApprovalDescMcpRead,
    ApprovalDescMcpAction,
    ApprovalDescAgent,
    ApprovalDescUnknown,
    // Approval impact summaries.
    ApprovalImpactSafe,
    ApprovalImpactFileWrite,
    ApprovalImpactShell,
    ApprovalImpactNetwork,
    ApprovalImpactMcpRead,
    ApprovalImpactMcpAction,
    ApprovalImpactAgent,
    ApprovalImpactUnknown,
    // Approval detail labels.
    ApprovalLabelCommand,
    ApprovalLabelDir,
    ApprovalLabelFile,
    ApprovalLabelPreview,
    ApprovalLabelProposedContent,
    ApprovalLabelReplaceThis,
    ApprovalLabelWithThis,
    ApprovalLabelReplacementContent,
    ApprovalLabelPath,
    ApprovalLabelTarget,
    ApprovalLabelInput,
    ApprovalLabelAction,
    ApprovalLabelType,
    ApprovalLabelPrompt,
    // Approval header labels.
    ApprovalLabelAbout,
    ApprovalLabelImpact,
    // Underwater shell phase words (footer status band).
    PhaseIdle,
    PhaseDraft,
    PhaseWorking,
    PhaseWaitingOnYou,
    PhaseDone,
    PhaseFailed,
    // Underwater header chips: mode and permission words.
    ChipPermissionAsk,
    ChipPermissionAutoApprove,
    // Underwater post-launch empty state.
    EmptyStateMcpLabel,
    // Fleet roster room.
    FleetRosterWorkers,
    // Sidebar work strip.
    SidebarTasksLabel,
    // Composer slash menu.
    ComposerSlashMenuHint,
    // Canonical transcript chrome.
    HistoryReasoningTitle,
    HistoryReasoningPlaceholder,
    HistoryReasoningHiddenActivity,
    HistoryReasoningStatusLive,
    HistoryReasoningStatusDone,
    HistorySystemNoteLabel,
    // Canonical exec terminal summaries.
    ExecModelRequestBudgetExhausted,
    ExecApiRequestBudgetExhausted,
    ExecTurnBudgetExhausted,
    ExecToolBudgetExhausted,
    ExecDepthLimitExceeded,
    ExecTimeout,
    ExecIncompleteModelStream,
    ExecContextLimitExceeded,
    ExecEmptyModelOutput,
    ExecOutputLimit,
    ExecContentFiltered,
    ExecInsufficientSystemResource,
    ExecOutputWriteFailed,
    ExecOutputQueueClosed,
    ExecOutputAcknowledgementDropped,
    ExecToolStarted,
    ExecToolCompleted,
    ExecToolFailed,
}

#[cfg(test)]
pub const ALL_MESSAGE_IDS: &[MessageId] = &[
    MessageId::ComposerPlaceholder,
    MessageId::CmdCostDescription,
    MessageId::CmdExitDescription,
    MessageId::CmdHelpDescription,
    MessageId::CmdCostReport,
    MessageId::CanonicalCommandRequired,
    MessageId::CanonicalCommandUnknown,
    MessageId::CanonicalCommandNoArguments,
    MessageId::CanonicalCommandListTitle,
    MessageId::CanonicalCommandAliases,
    MessageId::FooterWorkspacePrefix,
    MessageId::OnboardPanelTitle,
    MessageId::OnboardStepProgress,
    MessageId::OnboardHomeDirectoryNotFound,
    MessageId::OnboardWelcomeVersion,
    MessageId::OnboardWelcomeLead,
    MessageId::OnboardWelcomeSetupBlurb,
    MessageId::OnboardWelcomeSteps,
    MessageId::OnboardWelcomeStepApiKey,
    MessageId::OnboardWelcomeStepTrust,
    MessageId::OnboardWelcomeStepTips,
    MessageId::OnboardWelcomeDefaults,
    MessageId::OnboardWelcomeEnter,
    MessageId::OnboardWelcomeExit,
    MessageId::OnboardApiKeyTitle,
    MessageId::OnboardApiKeyStep1,
    MessageId::OnboardApiKeyStep2,
    MessageId::OnboardApiKeySavedHint,
    MessageId::OnboardApiKeyFormatHint,
    MessageId::OnboardApiKeyPlaceholder,
    MessageId::OnboardApiKeyLabel,
    MessageId::OnboardApiKeyFooter,
    MessageId::OnboardApiKeyEmpty,
    MessageId::OnboardApiKeyWhitespace,
    MessageId::OnboardApiKeyShortWarning,
    MessageId::OnboardApiKeyUnusualWarning,
    MessageId::OnboardTrustTitle,
    MessageId::OnboardTrustQuestion,
    MessageId::OnboardTrustLocationPrefix,
    MessageId::OnboardTrustRiskHint,
    MessageId::OnboardTrustEffectHint,
    MessageId::OnboardTrustFooterPrefix,
    MessageId::OnboardTrustFooterMiddle,
    MessageId::OnboardTrustFooterSuffix,
    MessageId::OnboardTrustConfirmHint,
    MessageId::OnboardTrustSaveFailed,
    MessageId::OnboardTipsTitle,
    MessageId::OnboardTipsLine1,
    MessageId::OnboardTipsLine2,
    MessageId::OnboardTipsLine3,
    MessageId::OnboardTipsLine4,
    MessageId::OnboardTipsFooterEnter,
    MessageId::OnboardTipsFooterAction,
    MessageId::CanonicalWorkspaceCanonicalizeFailed,
    MessageId::CanonicalWorkspaceNotDirectory,
    MessageId::CanonicalNoRecoverableRun,
    MessageId::CanonicalRecoveringInterruptedRun,
    MessageId::CanonicalInitialCommandConfirmation,
    MessageId::CanonicalUnknownValue,
    MessageId::CanonicalUnknownBillingCreation,
    MessageId::CanonicalAmbiguousPendingCreations,
    MessageId::CanonicalAmbiguousPendingCreationsMore,
    MessageId::CanonicalCancelAwaitTerminal,
    MessageId::CanonicalWaitTerminalBeforeExit,
    MessageId::CanonicalInterruptAccepted,
    MessageId::CanonicalWaitTerminal,
    MessageId::CanonicalCancelBeforeExit,
    MessageId::CanonicalHelpShown,
    MessageId::CanonicalCostShown,
    MessageId::CanonicalSteerSubmitFailed,
    MessageId::CanonicalWaitBeforeNextInput,
    MessageId::CanonicalRunSubmitFailed,
    MessageId::CanonicalLegacyActionUnavailable,
    MessageId::CanonicalMismatchedInteractionReceipt,
    MessageId::ApprovalRiskReview,
    MessageId::ApprovalRiskElevated,
    MessageId::ApprovalRiskDestructive,
    MessageId::ApprovalCategorySafe,
    MessageId::ApprovalCategoryFileWrite,
    MessageId::ApprovalCategoryShell,
    MessageId::ApprovalCategoryNetwork,
    MessageId::ApprovalCategoryMcpRead,
    MessageId::ApprovalCategoryMcpAction,
    MessageId::ApprovalCategoryAgent,
    MessageId::ApprovalCategoryUnknown,
    MessageId::ApprovalFieldType,
    MessageId::ApprovalFieldAbout,
    MessageId::ApprovalFieldImpact,
    MessageId::ApprovalFieldParams,
    MessageId::ApprovalOptionApproveOnce,
    MessageId::ApprovalOptionDeny,
    MessageId::ApprovalOptionAbortTurn,
    MessageId::ApprovalControlsHint,
    MessageId::ApprovalIntentLabel,
    MessageId::ApprovalMoreLines,
    MessageId::ApprovalEmptyContent,
    MessageId::ApprovalMorePatchLines,
    MessageId::ApprovalMoreFiles,
    MessageId::ApprovalUnknownFile,
    MessageId::ApprovalDescSafe,
    MessageId::ApprovalDescFileWrite,
    MessageId::ApprovalDescShell,
    MessageId::ApprovalDescNetwork,
    MessageId::ApprovalDescMcpRead,
    MessageId::ApprovalDescMcpAction,
    MessageId::ApprovalDescAgent,
    MessageId::ApprovalDescUnknown,
    MessageId::ApprovalImpactSafe,
    MessageId::ApprovalImpactFileWrite,
    MessageId::ApprovalImpactShell,
    MessageId::ApprovalImpactNetwork,
    MessageId::ApprovalImpactMcpRead,
    MessageId::ApprovalImpactMcpAction,
    MessageId::ApprovalImpactAgent,
    MessageId::ApprovalImpactUnknown,
    MessageId::ApprovalLabelCommand,
    MessageId::ApprovalLabelDir,
    MessageId::ApprovalLabelFile,
    MessageId::ApprovalLabelPreview,
    MessageId::ApprovalLabelProposedContent,
    MessageId::ApprovalLabelReplaceThis,
    MessageId::ApprovalLabelWithThis,
    MessageId::ApprovalLabelReplacementContent,
    MessageId::ApprovalLabelPath,
    MessageId::ApprovalLabelTarget,
    MessageId::ApprovalLabelInput,
    MessageId::ApprovalLabelAction,
    MessageId::ApprovalLabelType,
    MessageId::ApprovalLabelPrompt,
    MessageId::ApprovalLabelAbout,
    MessageId::ApprovalLabelImpact,
    MessageId::PhaseIdle,
    MessageId::PhaseDraft,
    MessageId::PhaseWorking,
    MessageId::PhaseWaitingOnYou,
    MessageId::PhaseDone,
    MessageId::PhaseFailed,
    MessageId::ChipPermissionAsk,
    MessageId::ChipPermissionAutoApprove,
    MessageId::EmptyStateMcpLabel,
    MessageId::FleetRosterWorkers,
    MessageId::SidebarTasksLabel,
    MessageId::ComposerSlashMenuHint,
    MessageId::HistoryReasoningTitle,
    MessageId::HistoryReasoningPlaceholder,
    MessageId::HistoryReasoningHiddenActivity,
    MessageId::HistoryReasoningStatusLive,
    MessageId::HistoryReasoningStatusDone,
    MessageId::HistorySystemNoteLabel,
    MessageId::ExecModelRequestBudgetExhausted,
    MessageId::ExecApiRequestBudgetExhausted,
    MessageId::ExecTurnBudgetExhausted,
    MessageId::ExecToolBudgetExhausted,
    MessageId::ExecDepthLimitExceeded,
    MessageId::ExecTimeout,
    MessageId::ExecIncompleteModelStream,
    MessageId::ExecContextLimitExceeded,
    MessageId::ExecEmptyModelOutput,
    MessageId::ExecOutputLimit,
    MessageId::ExecContentFiltered,
    MessageId::ExecInsufficientSystemResource,
    MessageId::ExecOutputWriteFailed,
    MessageId::ExecOutputQueueClosed,
    MessageId::ExecOutputAcknowledgementDropped,
    MessageId::ExecToolStarted,
    MessageId::ExecToolCompleted,
    MessageId::ExecToolFailed,
];

pub fn tr(id: MessageId) -> Cow<'static, str> {
    rust_i18n::t!(format!("{id:?}"), locale = "zh-Hans")
}

#[cfg(test)]
mod tests {
    use super::*;

    pub fn missing_message_ids() -> Vec<MessageId> {
        ALL_MESSAGE_IDS
            .iter()
            .copied()
            .filter(|id| tr(*id).eq(&format!("{id:?}")))
            .collect()
    }

    fn message_source() -> &'static str {
        include_str!("../locales/zh-Hans.json")
    }

    #[test]
    fn message_pack_has_no_missing_core_messages() {
        assert!(missing_message_ids().is_empty());
    }

    fn raw_message_keys() -> std::collections::BTreeSet<String> {
        serde_json::from_str::<serde_json::Map<String, serde_json::Value>>(message_source())
            .expect("zh-Hans message catalog should parse")
            .keys()
            .cloned()
            .collect()
    }

    #[test]
    fn message_id_list_and_catalog_stay_in_exact_sync() {
        let catalog = raw_message_keys();
        let ids: std::collections::BTreeSet<String> =
            ALL_MESSAGE_IDS.iter().map(|id| format!("{id:?}")).collect();
        assert_eq!(
            ids.len(),
            ALL_MESSAGE_IDS.len(),
            "ALL_MESSAGE_IDS contains duplicates"
        );
        let unlisted: Vec<_> = catalog.difference(&ids).collect();
        assert!(
            unlisted.is_empty(),
            "zh-Hans keys absent from ALL_MESSAGE_IDS: {unlisted:?}"
        );
        let missing: Vec<_> = ids.difference(&catalog).collect();
        assert!(
            missing.is_empty(),
            "ALL_MESSAGE_IDS entries without a zh-Hans string: {missing:?}"
        );
    }
}
